import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sideral SaaS - Factory",
  description: "Generated by SaaS Factory",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
